import{a as P,S as B,i}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="50322611-1d4a2dda66e83b148172da45e",$="https://pixabay.com/api/",x=15;async function u(o,t=1){const s={key:E,q:o,page:t,per_page:x,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await P.get($,{params:s})).data}catch{throw new Error("Failed to fetch images from Pixabay")}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new B(".gallery a");function h(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${q}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function O(){f.innerHTML=""}function p(){m.classList.add("active")}function g(){m.classList.remove("active")}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}const w=document.querySelector(".form");w.querySelector('input[name="search-text"]');const A=document.querySelector(".load-more");let l="",c=1,d=0;const v=15;w.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){i.warning({message:"Please enter a search query!"});return}c=1,O(),L(),p();try{const t=await u(l,c);if(d=t.totalHits,t.hits.length===0){i.info({message:"Sorry, no results found"});return}h(t.hits),d>v&&b()}catch{i.error({message:"Something went wrong"})}finally{g()}});A.addEventListener("click",async()=>{c+=1,p(),L();try{const o=await u(l,c);h(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),c*v>=d?i.info({message:"We're sorry, but you've reached the end of search results."}):b()}catch{i.error({message:"Something went wrong"})}finally{g()}});
//# sourceMappingURL=index.js.map
